use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsString;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use colored::Colorize;

use rbx_core::generated::GeneratedFile;

use crate::config::{CodegenStyle, Config};
use crate::lockfile::{EnvLock, Lockfile};

// ---------------------------------------------------------------------------
// Provenance banner
// ---------------------------------------------------------------------------

/// Header on every file this module emits.
///
/// Kept as constants rather than spelled out at each site: the banner is on its
/// way to being load-bearing — stale-file pruning refuses to delete anything
/// that does not carry `@generated` — and a copy that drifts would break that
/// recognition without failing anything.
///
/// Names the tool, not the subcommand, because `sync` and `codegen` both emit
/// this folder. `rbx env` names `gen-module` for the opposite reason: it is the
/// only thing there that writes a file.
const LUAU_HEADER: &str = "\
-- This file is automatically @generated by rbx shop.
-- It is not intended for manual editing.
";

const TS_HEADER: &str = "\
// This file is automatically @generated by rbx shop.
// It is not intended for manual editing.
";

/// The token the banner is recognized by. Nothing without it is ever deleted
/// as stale, so a hand-written file that wandered into the output folder is
/// left alone.
///
/// `@generated` rather than a product name: it is the convention review tools
/// recognize, and it survives the CLI being renamed.
const GENERATED_MARKER: &str = "@generated";

/// Same banner, naming the env the module carries. Worth the divergence: in
/// Studio the file is an instance inside a folder, so the header restates what
/// the file name says once the name is no longer in view.
fn luau_header_for_env(env_name: &str) -> String {
    format!(
        "-- This file is automatically @generated by rbx shop for env '{env_name}'.\n\
         -- It is not intended for manual editing.\n"
    )
}

// ---------------------------------------------------------------------------
// Reserved identifiers + key formatting
// ---------------------------------------------------------------------------

const LUAU_RESERVED: &[&str] = &[
    "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "if", "in", "local",
    "nil", "not", "or", "repeat", "return", "then", "true", "until", "while", "continue", "type",
    "export",
];

const TS_RESERVED: &[&str] = &[
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "new",
    "null",
    "return",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

fn is_valid_identifier(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

pub fn is_valid_luau_identifier(s: &str) -> bool {
    is_valid_identifier(s) && !LUAU_RESERVED.contains(&s)
}

fn is_valid_ts_identifier(s: &str) -> bool {
    is_valid_identifier(s) && !TS_RESERVED.contains(&s)
}

pub fn format_key(key: &str) -> String {
    if is_valid_luau_identifier(key) {
        key.to_string()
    } else {
        format!("[\"{}\"]", key.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

fn format_ts_key(key: &str) -> String {
    if is_valid_ts_identifier(key) {
        key.to_string()
    } else {
        format!("\"{}\"", key.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

/// Format a key for the LHS of a Luau type field. Quoted form for non-idents.
fn format_luau_type_key(key: &str) -> String {
    if is_valid_luau_identifier(key) {
        key.to_string()
    } else {
        format!("[\"{}\"]", key.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

// ---------------------------------------------------------------------------
// Tree types — per-env IDs and the shape union
// ---------------------------------------------------------------------------

pub type CodegenTree = BTreeMap<String, CodegenNode>;

#[derive(Debug)]
pub enum CodegenNode {
    Leaf(u64),
    Branch(BTreeMap<String, CodegenNode>),
}

/// Same shape as `CodegenTree` but stripped of leaf values, used to describe
/// the union of all envs' shapes for type emission and 0-stub padding.
pub type ShapeTree = BTreeMap<String, ShapeNode>;

#[derive(Debug)]
pub enum ShapeNode {
    Leaf,
    Branch(BTreeMap<String, ShapeNode>),
}

fn insert_into_tree(tree: &mut CodegenTree, segments: &[&str], key: &str, id: u64) {
    if segments.is_empty() {
        tree.insert(key.to_string(), CodegenNode::Leaf(id));
        return;
    }
    let node = tree
        .entry(segments[0].to_string())
        .or_insert_with(|| CodegenNode::Branch(BTreeMap::new()));
    match node {
        CodegenNode::Branch(children) => {
            insert_into_tree(children, &segments[1..], key, id);
        }
        CodegenNode::Leaf(_) => {
            let mut children = BTreeMap::new();
            insert_into_tree(&mut children, &segments[1..], key, id);
            *node = CodegenNode::Branch(children);
        }
    }
}

fn insert_item(tree: &mut CodegenTree, path_str: &str, key: &str, id: u64, flat: bool) {
    if flat {
        let flat_key = format!("{path_str}.{key}");
        tree.insert(flat_key, CodegenNode::Leaf(id));
    } else {
        let segments: Vec<&str> = path_str.split('.').collect();
        insert_into_tree(tree, &segments, key, id);
    }
}

fn resolve_path<'a>(item_path: Option<&'a str>, section_default: &'a str) -> &'a str {
    item_path.unwrap_or(section_default)
}

/// Build a CodegenTree for a single env from its lockfile section + the
/// config-level codegen options.
pub fn build_env_tree(env_lock: &EnvLock, config: &Config) -> CodegenTree {
    let mut tree = CodegenTree::new();
    let flat = config.codegen.style == CodegenStyle::Flat;

    let default_pass_path = config.codegen.paths.passes.as_deref().unwrap_or("passes");
    let default_badge_path = config.codegen.paths.badges.as_deref().unwrap_or("badges");
    let default_product_path = config
        .codegen
        .paths
        .products
        .as_deref()
        .unwrap_or("products");

    for (key, lock) in &env_lock.passes {
        let path_str = resolve_path(
            config.passes.get(key).and_then(|c| c.path.as_deref()),
            default_pass_path,
        );
        insert_item(&mut tree, path_str, key, lock.id, flat);
    }

    for (key, lock) in &env_lock.badges {
        let path_str = resolve_path(
            config.badges.get(key).and_then(|c| c.path.as_deref()),
            default_badge_path,
        );
        insert_item(&mut tree, path_str, key, lock.id, flat);
    }

    for (key, lock) in &env_lock.products {
        let path_str = resolve_path(
            config.products.get(key).and_then(|c| c.path.as_deref()),
            default_product_path,
        );
        insert_item(&mut tree, path_str, key, lock.id, flat);
    }

    for (full_key, &id) in &config.codegen.extra {
        if flat {
            tree.insert(full_key.clone(), CodegenNode::Leaf(id));
        } else if let Some(dot_pos) = full_key.rfind('.') {
            let path_str = &full_key[..dot_pos];
            let leaf_key = &full_key[dot_pos + 1..];
            let segments: Vec<&str> = path_str.split('.').collect();
            insert_into_tree(&mut tree, &segments, leaf_key, id);
        } else {
            tree.insert(full_key.clone(), CodegenNode::Leaf(id));
        }
    }

    tree
}

// ---------------------------------------------------------------------------
// Shape union + 0-stub padding
// ---------------------------------------------------------------------------

fn extract_shape(tree: &CodegenTree) -> ShapeTree {
    let mut out = ShapeTree::new();
    for (k, v) in tree {
        match v {
            CodegenNode::Leaf(_) => {
                out.insert(k.clone(), ShapeNode::Leaf);
            }
            CodegenNode::Branch(children) => {
                out.insert(k.clone(), ShapeNode::Branch(extract_shape(children)));
            }
        }
    }
    out
}

fn merge_shape(into: &mut ShapeTree, other: &ShapeTree) {
    for (k, v) in other {
        match (into.get_mut(k), v) {
            (Some(ShapeNode::Branch(into_children)), ShapeNode::Branch(other_children)) => {
                merge_shape(into_children, other_children);
            }
            (Some(ShapeNode::Leaf), ShapeNode::Leaf) => {}
            (Some(_), _) => {
                // Conflicting kinds (leaf vs branch) — keep `into`'s kind.
                // Should not happen with well-formed configs.
            }
            (None, ShapeNode::Leaf) => {
                into.insert(k.clone(), ShapeNode::Leaf);
            }
            (None, ShapeNode::Branch(children)) => {
                into.insert(k.clone(), ShapeNode::Branch(clone_shape(children)));
            }
        }
    }
}

fn clone_shape(children: &ShapeTree) -> ShapeTree {
    let mut out = ShapeTree::new();
    for (k, v) in children {
        out.insert(
            k.clone(),
            match v {
                ShapeNode::Leaf => ShapeNode::Leaf,
                ShapeNode::Branch(c) => ShapeNode::Branch(clone_shape(c)),
            },
        );
    }
    out
}

/// Walk `shape` and ensure every leaf path is present in `tree` (inserting
/// `Leaf(0)` for missing ones).
fn pad_with_zeros(tree: &mut CodegenTree, shape: &ShapeTree) {
    for (k, sv) in shape {
        match sv {
            ShapeNode::Leaf => {
                if !tree.contains_key(k) {
                    tree.insert(k.clone(), CodegenNode::Leaf(0));
                }
            }
            ShapeNode::Branch(shape_children) => {
                let entry = tree
                    .entry(k.clone())
                    .or_insert_with(|| CodegenNode::Branch(BTreeMap::new()));
                if let CodegenNode::Branch(tree_children) = entry {
                    pad_with_zeros(tree_children, shape_children);
                }
            }
        }
    }
}

/// Build the union shape across all envs.
fn build_union_shape(env_trees: &[(String, CodegenTree)]) -> ShapeTree {
    let mut union = ShapeTree::new();
    for (_, tree) in env_trees {
        let shape = extract_shape(tree);
        merge_shape(&mut union, &shape);
    }
    union
}

// ---------------------------------------------------------------------------
// Rendering — per-env Luau module (value tables)
// ---------------------------------------------------------------------------

fn render_luau_value_node(out: &mut String, node: &CodegenNode, depth: usize) {
    let indent = "\t".repeat(depth);
    match node {
        CodegenNode::Leaf(id) => {
            out.push_str(&format!("{id},\n"));
        }
        CodegenNode::Branch(children) => {
            out.push_str("{\n");
            for (key, child) in children {
                out.push_str(&format!("{indent}\t{} = ", format_key(key)));
                render_luau_value_node(out, child, depth + 1);
            }
            out.push_str(&format!("{indent}}},\n"));
        }
    }
}

fn render_env_module(
    tree: &CodegenTree,
    env_name: &str,
    has_stubs: bool,
    type_module_name: &str,
    wrapper_name: &str,
) -> String {
    let mut out = String::new();
    out.push_str(&luau_header_for_env(env_name));
    if has_stubs {
        // Worth the one extra line: a reader who finds `VIP = 0` has no other
        // way to tell a stub from a real id, and prompting one is a silent
        // no-op rather than an error.
        out.push_str("-- Entries with the value 0 are stubs: absent from this env.\n");
    }
    out.push('\n');
    out.push_str(&format!(
        "local Types = require(script.Parent.{})\n\n",
        type_module_name
    ));
    out.push_str(&format!("return Types.{}({{\n", wrapper_name));
    for (key, node) in tree {
        out.push_str(&format!("\t{} = ", format_key(key)));
        render_luau_value_node(&mut out, node, 1);
    }
    out.push_str("})\n");
    out
}

/// Render the Type module that holds `export type <Name>` plus the wrapper
/// identity function used by per-env modules for compile-time shape validation.
fn render_type_module(
    shape: &ShapeTree,
    var_name: &str,
    wrapper_name: &str,
    style_is_flat: bool,
) -> String {
    let mut out = String::new();
    out.push_str(LUAU_HEADER);
    out.push('\n');

    // Type alias
    out.push_str(&format!("export type {} = ", var_name));
    if style_is_flat {
        out.push_str("{\n");
        for key in shape.keys() {
            out.push_str(&format!("\t{}: number,\n", format_luau_type_key(key)));
        }
        out.push_str("}\n\n");
    } else {
        out.push_str("{\n");
        for (key, node) in shape {
            out.push_str(&format!("\t{}: ", format_luau_type_key(key)));
            render_luau_type_node(&mut out, node, 1);
        }
        out.push_str("}\n\n");
    }

    // Wrapper identity function — Luau-strict mode validates the literal at
    // every call site against the type.
    out.push_str(&format!(
        "local function {wrapper}(x: {ty}): {ty}\n\treturn x\nend\n\n",
        wrapper = wrapper_name,
        ty = var_name,
    ));

    out.push_str(&format!(
        "return {{\n\t{} = {},\n}}\n",
        wrapper_name, wrapper_name
    ));
    out
}

fn tree_contains_zero(tree: &CodegenTree) -> bool {
    for v in tree.values() {
        match v {
            CodegenNode::Leaf(0) => return true,
            CodegenNode::Branch(children) if tree_contains_zero(children) => return true,
            _ => {}
        }
    }
    false
}

// ---------------------------------------------------------------------------
// Rendering — init.luau (type alias + dispatcher)
// ---------------------------------------------------------------------------

fn render_luau_type_node(out: &mut String, node: &ShapeNode, depth: usize) {
    let indent = "\t".repeat(depth);
    match node {
        ShapeNode::Leaf => {
            out.push_str("number,\n");
        }
        ShapeNode::Branch(children) => {
            out.push_str("{\n");
            for (key, child) in children {
                out.push_str(&format!("{indent}\t{}: ", format_luau_type_key(key)));
                render_luau_type_node(out, child, depth + 1);
            }
            out.push_str(&format!("{indent}}},\n"));
        }
    }
}

fn render_init_luau(
    env_universes: &[(String, u64)],
    var_name: &str,
    type_module_name: &str,
) -> String {
    let mut out = String::new();
    out.push_str(LUAU_HEADER);
    out.push('\n');

    // Re-export the type from the sibling Types module so consumers can do
    // `type Ids = GameIds.<var_name>` after a single require.
    out.push_str(&format!(
        "local Types = require(script.{})\n",
        type_module_name
    ));
    out.push_str(&format!(
        "export type {name} = Types.{name}\n\n",
        name = var_name
    ));

    // String-literal union of env names — required for `never`-exhaustiveness
    // narrowing in the if/elseif dispatcher below.
    out.push_str("export type EnvName = ");
    let env_literals: Vec<String> = env_universes
        .iter()
        .map(|(name, _)| format!("\"{}\"", name.replace('"', "\\\"")))
        .collect();
    out.push_str(&env_literals.join(" | "));
    out.push_str("\n\n");

    // Universe → env lookup. The value type is EnvName (not a plain string)
    // so the narrowing in the dispatcher works.
    out.push_str("local UNIVERSE_TO_ENV: { [number]: EnvName } = {\n");
    for (env_name, universe_id) in env_universes {
        out.push_str(&format!(
            "\t[{}] = \"{}\",\n",
            universe_id,
            env_name.replace('"', "\\\"")
        ));
    }
    out.push_str("}\n\n");

    // Exhaustiveness helper. Calling this with a `never` argument is only
    // type-safe when every variant of EnvName has been narrowed away by an
    // earlier branch. Adding a new env to EnvName without an accompanying
    // elseif fails to compile in strict mode.
    out.push_str(
        "local function exhaustiveMatch(value: never): never\n\
         \terror(`rbxshop: unhandled env in dispatcher: {value :: any}`)\n\
         end\n\n",
    );

    // Resolve the env from the running universe.
    out.push_str("local env = UNIVERSE_TO_ENV[game.GameId]\n");
    out.push_str("if not env then\n");
    out.push_str("\terror(`rbxshop: unknown universe {game.GameId}`)\n");
    out.push_str("end\n\n");

    // if/elseif/else dispatcher with exhaustive fallback.
    for (idx, (env_name, _)) in env_universes.iter().enumerate() {
        let keyword = if idx == 0 { "if" } else { "elseif" };
        let env_child = if is_valid_luau_identifier(env_name) {
            format!("script.{}", env_name)
        } else {
            format!("script[\"{}\"]", env_name.replace('"', "\\\""))
        };
        out.push_str(&format!(
            "{} env == \"{}\" then\n\treturn require({})\n",
            keyword,
            env_name.replace('"', "\\\""),
            env_child
        ));
    }
    out.push_str(
        "else\n\
         \texhaustiveMatch(env)\n\
         \terror(\"luau\")\n\
         end\n",
    );

    out
}

// ---------------------------------------------------------------------------
// Rendering — TypeScript (.d.ts)
// ---------------------------------------------------------------------------

fn render_ts_type_node(out: &mut String, node: &ShapeNode, depth: usize) {
    let indent = "\t".repeat(depth);
    match node {
        ShapeNode::Leaf => {
            out.push_str("number\n");
        }
        ShapeNode::Branch(children) => {
            out.push_str("{\n");
            for (key, child) in children {
                out.push_str(&format!("{indent}\t{}: ", format_ts_key(key)));
                render_ts_type_node(out, child, depth + 1);
            }
            out.push_str(&format!("{indent}}}\n"));
        }
    }
}

fn render_init_dts(shape: &ShapeTree, var_name: &str, style_is_flat: bool) -> String {
    let mut out = String::new();
    out.push_str(TS_HEADER);
    out.push('\n');
    out.push_str(&format!("declare const {}: {{\n", var_name));
    if style_is_flat {
        for key in shape.keys() {
            out.push_str(&format!("\t{}: number\n", format_ts_key(key)));
        }
    } else {
        for (key, node) in shape {
            out.push_str(&format!("\t{}: ", format_ts_key(key)));
            render_ts_type_node(&mut out, node, 1);
        }
    }
    out.push_str("}\n\n");
    out.push_str(&format!("export = {}\n", var_name));
    out
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Derive the Luau type/variable name from the output folder path.
/// Defaults to "GameIds" if the path has no useful component or the component
/// isn't a valid Luau identifier.
fn derive_var_name(output_path: &Path) -> String {
    output_path
        .file_name()
        .and_then(|s| s.to_str())
        .filter(|s| is_valid_luau_identifier(s))
        .map(|s| s.to_string())
        .unwrap_or_else(|| "GameIds".to_string())
}

/// Lower-case the first ASCII character, keep the rest unchanged.
/// `"GameIds"` → `"gameIds"`, `"Assets"` → `"assets"`.
fn lower_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_ascii_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/// Everything a codegen run would do, computed without touching the
/// filesystem beyond looking for leftovers.
///
/// `generate` and `codegen --check` both go through this, which is the whole
/// point: a verifier that re-described what the writer emits would drift from
/// it, and a check with false positives gets switched off.
#[derive(Debug)]
pub struct CodegenPlan {
    /// Absolute path of the output folder.
    pub dir: PathBuf,
    /// Files this run produces, in write order.
    pub files: Vec<GeneratedFile>,
    /// Files we generated previously that this run no longer produces — a
    /// renamed or deleted env, or `typescript` turned off. Left behind, they
    /// are dead modules that still look generated.
    pub stale: Vec<PathBuf>,
    /// Number of envs rendered.
    pub env_count: usize,
}

/// Compute the codegen plan. `Ok(None)` when there is nothing to generate:
/// either `[codegen].output` is unset, or the lockfile has no envs yet.
pub fn plan(
    config: &Config,
    lockfile: &Lockfile,
    config_dir: &Path,
) -> Result<Option<CodegenPlan>> {
    let Some(output) = &config.codegen.output else {
        return Ok(None);
    };
    let output_path = config_dir.join(output);

    if let Some(name) = output.file_name().and_then(|s| s.to_str()) {
        let lower = name.to_ascii_lowercase();
        let stripped_len = if lower.ends_with(".luau") {
            Some(name.len() - 5)
        } else if lower.ends_with(".lua") {
            Some(name.len() - 4)
        } else {
            None
        };
        if let Some(len) = stripped_len {
            bail!(
                "[codegen].output = \"{}\" looks like a file path, not a folder — it names a \
                 FOLDER that will contain init.luau and per-env modules, so it shouldn't end in \
                 a Luau extension. Remove the extension, e.g. \"{}\".",
                output.display(),
                output.with_file_name(&name[..len]).display()
            );
        }
    }

    if lockfile.envs.is_empty() {
        return Ok(None);
    }

    // Names derived from the folder name (PascalCase by convention).
    //   output = "src/shared/GameIds" → var_name = "GameIds"
    //   wrapper_name = lower-first → "gameIds"
    //   type_module_name = "<var_name>Type" → "GameIdsType"
    let var_name = derive_var_name(&output_path);
    let wrapper_name = lower_first(&var_name);
    let type_module_name = format!("{}Type", var_name);

    // Per-env modules are written as `<env>.luau` next to init.luau and the
    // type module — an env named after either would silently clobber it.
    for env_name in lockfile.envs.keys() {
        if env_name == "init" || *env_name == type_module_name {
            bail!(
                "Env name '{env_name}' collides with the generated {env_name}.luau module. \
                 Rename the env in rbxplace.toml or change codegen.output."
            );
        }
        if env_name.contains(['/', '\\']) || env_name == "." || env_name == ".." {
            bail!("Env name '{env_name}' is not usable as a codegen file name.");
        }
    }

    // Build per-env trees
    let mut env_trees: Vec<(String, CodegenTree)> = Vec::new();
    let mut env_universes: Vec<(String, u64)> = Vec::new();
    for (env_name, env_lock) in &lockfile.envs {
        let tree = build_env_tree(env_lock, config);
        env_trees.push((env_name.clone(), tree));
        env_universes.push((env_name.clone(), env_lock.universe_id));
    }

    // Compute union shape and pad each env tree with 0-stubs for missing entries.
    let union_shape = build_union_shape(&env_trees);
    for (_, tree) in &mut env_trees {
        pad_with_zeros(tree, &union_shape);
    }

    let style_is_flat = config.codegen.style == CodegenStyle::Flat;

    let mut files = Vec::new();

    // <var_name>Type.luau (type + wrapper function)
    files.push(GeneratedFile::new(
        output_path.join(format!("{}.luau", type_module_name)),
        render_type_module(&union_shape, &var_name, &wrapper_name, style_is_flat),
    ));

    // init.luau (dispatcher)
    files.push(GeneratedFile::new(
        output_path.join("init.luau"),
        render_init_luau(&env_universes, &var_name, &type_module_name),
    ));

    // Per-env modules (each wraps its data with Types.<wrapper>(...))
    for (env_name, tree) in &env_trees {
        let has_stubs = tree_contains_zero(tree);
        files.push(GeneratedFile::new(
            output_path.join(format!("{}.luau", env_name)),
            render_env_module(tree, env_name, has_stubs, &type_module_name, &wrapper_name),
        ));
    }

    // init.d.ts if requested
    if config.codegen.typescript {
        files.push(GeneratedFile::new(
            output_path.join("init.d.ts"),
            render_init_dts(&union_shape, &var_name, style_is_flat),
        ));
    }

    let stale = find_stale(&output_path, &files)?;

    Ok(Some(CodegenPlan {
        dir: output_path,
        files,
        stale,
        env_count: env_trees.len(),
    }))
}

/// Files in `dir` that we generated on an earlier run but that this plan no
/// longer produces.
///
/// Only files that could plausibly be ours are considered, and each one must
/// still carry [`GENERATED_MARKER`] in its header — pruning deletes files, so
/// it errs entirely on the side of leaving things alone.
fn find_stale(dir: &Path, files: &[GeneratedFile]) -> Result<Vec<PathBuf>> {
    if !dir.is_dir() {
        return Ok(Vec::new());
    }

    let expected: BTreeSet<OsString> = files
        .iter()
        .filter_map(|f| f.path.file_name().map(|n| n.to_os_string()))
        .collect();

    let mut stale = Vec::new();
    let entries = std::fs::read_dir(dir)
        .with_context(|| format!("Failed to read codegen folder {}", dir.display()))?;

    for entry in entries {
        let entry = entry?;
        if !entry.file_type()?.is_file() {
            continue;
        }
        let name = entry.file_name();
        if expected.contains(&name) {
            continue;
        }
        let Some(name) = name.to_str() else { continue };
        let could_be_ours = name.ends_with(".luau") || name.ends_with(".d.ts");
        if !could_be_ours {
            continue;
        }
        if is_generated(&entry.path()) {
            stale.push(entry.path());
        }
    }

    stale.sort();
    Ok(stale)
}

/// Whether a file carries our header. Unreadable files answer `false`: better
/// to leave a stale module behind than to delete something we did not write.
fn is_generated(path: &Path) -> bool {
    std::fs::read_to_string(path)
        .map(|content| {
            content
                .lines()
                .take(4)
                .any(|line| line.contains(GENERATED_MARKER))
        })
        .unwrap_or(false)
}

/// Render and write the codegen folder, pruning anything we generated
/// previously that the current inputs no longer produce.
pub fn generate(config: &Config, lockfile: &Lockfile, config_dir: &Path) -> Result<()> {
    let Some(plan) = plan(config, lockfile, config_dir)? else {
        return Ok(());
    };

    std::fs::create_dir_all(&plan.dir)
        .with_context(|| format!("Failed to create codegen folder {}", plan.dir.display()))?;

    for file in &plan.files {
        file.write()?;
    }

    for path in &plan.stale {
        std::fs::remove_file(path)
            .with_context(|| format!("Failed to remove stale {}", path.display()))?;
        println!("{} Removed stale {}", "-".yellow(), path.display());
    }

    println!(
        "{} Generated codegen at {} ({} env{})",
        "✓".green(),
        plan.dir.display(),
        plan.env_count,
        if plan.env_count == 1 { "" } else { "s" }
    );

    Ok(())
}
