#![allow(clippy::unwrap_used)]
//! `rbx env rm` — what it removes, what it leaves alone, and what it refuses.
//!
//! Driven through `commands::rm::run` against a temporary project, because the
//! properties worth pinning are all about files on disk: which ones changed,
//! which bytes survived, and whether a failure left a half-edited project
//! behind.

use std::path::Path;

use rbx_env::commands::rm;
use tempfile::TempDir;

/// A project with two envs declared everywhere an env can be declared, and a
/// comment in each hand-written file so the round trip can be checked.
fn project() -> TempDir {
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path();

    std::fs::write(
        p.join("rbxplace.toml"),
        r#"# the map every command resolves --env against
[owner]
type = "user"
id = 1

[dev]
universe_id = 100

[prod]
universe_id = 200
"#,
    )
    .unwrap();

    std::fs::write(
        p.join("rbxmeta.toml"),
        r#"[game]
name = "Test"  # keep me

[envs.dev]
name = "Test (dev)"

[envs.prod]
name = "Test"
"#,
    )
    .unwrap();

    std::fs::write(
        p.join("rbxshop.toml"),
        r#"[codegen]
output = "src/GameIds"

[passes.VIP]
price = 499

[envs.dev.passes.VIP]
price = 1

[envs.prod.passes.VIP]
price = 499
"#,
    )
    .unwrap();

    std::fs::write(
        p.join("rbxshop.lock.toml"),
        r#"version = 2

[envs.dev]
universe_id = 100

[envs.dev.passes.VIP]
id = 11
name = "VIP"
price = 1

[envs.prod]
universe_id = 200

[envs.prod.passes.VIP]
id = 12
name = "VIP"
price = 499
"#,
    )
    .unwrap();

    std::fs::write(
        p.join("rbxmeta.lock.toml"),
        r#"version = 1

[envs.dev]
universe_id = 100
place_id = 1000

[envs.prod]
universe_id = 200
place_id = 2000
"#,
    )
    .unwrap();

    std::fs::create_dir_all(p.join("src/GameIds")).unwrap();
    for env in ["dev", "prod"] {
        std::fs::write(
            p.join("src/GameIds").join(format!("{env}.luau")),
            "-- This file is automatically @generated by rbx shop.\nreturn {}\n",
        )
        .unwrap();
    }

    dir
}

fn read(dir: &Path, name: &str) -> String {
    std::fs::read_to_string(dir.join(name)).unwrap()
}

fn places(dir: &Path) -> std::path::PathBuf {
    dir.join("rbxplace.toml")
}

#[test]
fn removing_an_env_clears_it_from_every_file() {
    let dir = project();
    let p = dir.path();

    rm::run(&places(p), "dev", false, true).unwrap();

    for file in [
        "rbxplace.toml",
        "rbxmeta.toml",
        "rbxshop.toml",
        "rbxshop.lock.toml",
        "rbxmeta.lock.toml",
    ] {
        let text = read(p, file);
        assert!(!text.contains("dev"), "{file} still mentions dev:\n{text}");
    }
    assert!(!p.join("src/GameIds/dev.luau").exists());
}

/// The other env is the control. A command that removed everything would pass
/// the test above.
#[test]
fn the_other_env_is_untouched() {
    let dir = project();
    let p = dir.path();

    rm::run(&places(p), "dev", false, true).unwrap();

    assert!(read(p, "rbxplace.toml").contains("[prod]"));
    assert!(read(p, "rbxmeta.toml").contains("[envs.prod]"));
    assert!(read(p, "rbxshop.toml").contains("[envs.prod.passes.VIP]"));
    assert!(read(p, "rbxshop.lock.toml").contains("id = 12"));
    assert!(read(p, "rbxmeta.lock.toml").contains("place_id = 2000"));
    assert!(p.join("src/GameIds/prod.luau").exists());
}

/// These are files people write by hand. Reserialising the model through serde
/// would have dropped the comments and reordered the keys, which is the whole
/// reason this edits documents instead.
#[test]
fn comments_and_unrelated_tables_survive() {
    let dir = project();
    let p = dir.path();

    rm::run(&places(p), "dev", false, true).unwrap();

    let places_text = read(p, "rbxplace.toml");
    assert!(places_text.contains("# the map every command resolves"));
    assert!(places_text.contains("[owner]"));

    let meta = read(p, "rbxmeta.toml");
    assert!(meta.contains("# keep me"), "{meta}");
    assert!(meta.contains("[game]"));

    let shop = read(p, "rbxshop.toml");
    assert!(shop.contains("[passes.VIP]"), "{shop}");
    assert!(shop.contains(r#"output = "src/GameIds""#));
}

/// A typo must not report success having done nothing. Removal is the one
/// operation where "no match" and "done" have to be different answers.
#[test]
fn an_unknown_env_is_refused_and_names_the_ones_that_exist() {
    let dir = project();
    let p = dir.path();

    let err = rm::run(&places(p), "staging", false, true)
        .unwrap_err()
        .to_string();

    assert!(err.contains("staging"), "{err}");
    assert!(err.contains("dev"), "{err}");
    assert!(err.contains("prod"), "{err}");
    // And nothing moved.
    assert!(read(p, "rbxplace.toml").contains("[dev]"));
}

/// `[owner]` and `[codegen]` are top-level tables in `rbxplace.toml` that are
/// not envs. Matching on table names alone would delete them.
#[test]
fn a_top_level_table_that_is_not_an_env_is_refused() {
    let dir = project();
    let p = dir.path();

    assert!(rm::run(&places(p), "owner", false, true).is_err());
    assert!(read(p, "rbxplace.toml").contains("[owner]"));
}

#[test]
fn a_dry_run_changes_nothing() {
    let dir = project();
    let p = dir.path();
    let before: Vec<String> = [
        "rbxplace.toml",
        "rbxmeta.toml",
        "rbxshop.toml",
        "rbxshop.lock.toml",
        "rbxmeta.lock.toml",
    ]
    .iter()
    .map(|f| read(p, f))
    .collect();

    rm::run(&places(p), "dev", true, true).unwrap();

    let after: Vec<String> = [
        "rbxplace.toml",
        "rbxmeta.toml",
        "rbxshop.toml",
        "rbxshop.lock.toml",
        "rbxmeta.lock.toml",
    ]
    .iter()
    .map(|f| read(p, f))
    .collect();

    assert_eq!(before, after);
    assert!(p.join("src/GameIds/dev.luau").exists());
}

/// A project with no shop and no meta config is the ordinary case for someone
/// who only uses `rbx place`. The absent files are not an error.
#[test]
fn files_that_do_not_exist_are_not_an_error() {
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path();
    std::fs::write(
        p.join("rbxplace.toml"),
        "[dev]\nuniverse_id = 100\n\n[prod]\nuniverse_id = 200\n",
    )
    .unwrap();

    rm::run(&places(p), "dev", false, true).unwrap();

    let text = read(p, "rbxplace.toml");
    assert!(!text.contains("[dev]"));
    assert!(text.contains("[prod]"));
}

/// Removing the last env from an overlay should not leave an empty `[envs]`
/// table behind in a file somebody reads.
#[test]
fn an_emptied_envs_table_is_removed_too() {
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path();
    std::fs::write(
        p.join("rbxplace.toml"),
        "[dev]\nuniverse_id = 100\n\n[prod]\nuniverse_id = 200\n",
    )
    .unwrap();
    std::fs::write(
        p.join("rbxmeta.toml"),
        "[game]\nname = \"Test\"\n\n[envs.dev]\nname = \"Test (dev)\"\n",
    )
    .unwrap();

    rm::run(&places(p), "dev", false, true).unwrap();

    let meta = read(p, "rbxmeta.toml");
    assert!(!meta.contains("envs"), "{meta}");
    assert!(meta.contains("[game]"));
}

/// An `envs` table written inline is still an `envs` table.
///
/// `toml_edit` reports `envs = { dev = { … } }` as absent to `as_table`, so the
/// env was skipped in silence: the plan omitted the file and the command
/// reported success anyway. For a command whose stated promise is "every file
/// that mentions it", reporting a removal it did not perform is the worst
/// available failure.
#[test]
fn an_inline_envs_table_is_not_skipped() {
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path();
    std::fs::write(
        p.join("rbxplace.toml"),
        "[dev]\nuniverse_id = 100\n\n[prod]\nuniverse_id = 200\n",
    )
    .unwrap();
    std::fs::write(
        p.join("rbxmeta.toml"),
        // Before `[game]`, not after: an inline `envs` written below a table
        // header belongs to *that* table, not to the document root. Getting
        // this wrong is how the `genre` swallowing was found in the first
        // place, and it is easy enough to repeat that the placement is worth a
        // comment.
        "envs = { dev = { name = \"dev name\" }, prod = { name = \"prod name\" } }\n\n[game]\nname = \"Test\"\n",
    )
    .unwrap();

    rm::run(&places(p), "dev", false, true).unwrap();

    let meta = read(p, "rbxmeta.toml");
    assert!(!meta.contains("dev name"), "dev survived inline:\n{meta}");
    assert!(meta.contains("prod name"), "prod was taken too:\n{meta}");
}

// Deleted rather than kept: the version here asserted only that a dry run
// writes nothing, which is true whether or not `holds` sees an inline table —
// a dry run writes nothing either way. It stayed green against the bug it was
// named for. `an_inline_envs_table_is_not_skipped` above is the one with
// teeth, checked by restoring `as_table` and watching it go red.
//
// Testing what the deleted name promised means observing the printed plan,
// which needs `run` to return the removals rather than only printing them.
// Worth doing when something else needs that shape; not worth a signature
// change on its own.
